### ISSUE TITLE
Typo ‘Languague’ in language spec file

### ISSUE THREAD

**Issue by hanaral** [greyhat-academy/yadl#1]
It’s on line 3, and says ‘… Languague’ rather than ‘… Language’.

**Comment by kkarhan** [comment]
thanks.

has been fixed with the latest commit:
https://github.com/greyhat-academy/yadl/commit/b584caaa79e167b6295cc601e92a0075a637c38b

**Comment by kkarhan** [comment]
you may find further info in 
https://github.com/greyhat-academy/yadl/blob/main/README.md
